package com.pharmacy.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "shift_handovers")
public class ShiftHandover {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "outgoing_staff_id")
    private Staff outgoingStaff;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "incoming_staff_id")
    private Staff incomingStaff;

    @Column(nullable = false)
    private String shiftType; // MORNING, AFTERNOON, NIGHT

    @Column(length = 5000)
    private String handoverNotes;

    @Column(length = 5000)
    private String aiSummary; // auto-generated by AI

    @Column(length = 2000)
    private String criticalAlerts; // low stock + expiry warnings at time of handover

    private int stockTransactionsDone;
    private int prescriptionsDispensed;
    private int lowStockCount;
    private int expiringCount;

    @Enumerated(EnumType.STRING)
    private HandoverStatus status = HandoverStatus.PENDING;

    private LocalDateTime createdAt;
    private LocalDateTime acknowledgedAt;

    // Default constructor
    public ShiftHandover() {}

    // Constructor with all fields
    public ShiftHandover(Long id, Staff outgoingStaff, Staff incomingStaff, String shiftType, String handoverNotes, String aiSummary, String criticalAlerts, int stockTransactionsDone, int prescriptionsDispensed, int lowStockCount, int expiringCount, HandoverStatus status, LocalDateTime createdAt, LocalDateTime acknowledgedAt) {
        this.id = id;
        this.outgoingStaff = outgoingStaff;
        this.incomingStaff = incomingStaff;
        this.shiftType = shiftType;
        this.handoverNotes = handoverNotes;
        this.aiSummary = aiSummary;
        this.criticalAlerts = criticalAlerts;
        this.stockTransactionsDone = stockTransactionsDone;
        this.prescriptionsDispensed = prescriptionsDispensed;
        this.lowStockCount = lowStockCount;
        this.expiringCount = expiringCount;
        this.status = status;
        this.createdAt = createdAt;
        this.acknowledgedAt = acknowledgedAt;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Staff getOutgoingStaff() { return outgoingStaff; }
    public void setOutgoingStaff(Staff outgoingStaff) { this.outgoingStaff = outgoingStaff; }

    public Staff getIncomingStaff() { return incomingStaff; }
    public void setIncomingStaff(Staff incomingStaff) { this.incomingStaff = incomingStaff; }

    public String getShiftType() { return shiftType; }
    public void setShiftType(String shiftType) { this.shiftType = shiftType; }

    public String getHandoverNotes() { return handoverNotes; }
    public void setHandoverNotes(String handoverNotes) { this.handoverNotes = handoverNotes; }

    public String getAiSummary() { return aiSummary; }
    public void setAiSummary(String aiSummary) { this.aiSummary = aiSummary; }

    public String getCriticalAlerts() { return criticalAlerts; }
    public void setCriticalAlerts(String criticalAlerts) { this.criticalAlerts = criticalAlerts; }

    public int getStockTransactionsDone() { return stockTransactionsDone; }
    public void setStockTransactionsDone(int stockTransactionsDone) { this.stockTransactionsDone = stockTransactionsDone; }

    public int getPrescriptionsDispensed() { return prescriptionsDispensed; }
    public void setPrescriptionsDispensed(int prescriptionsDispensed) { this.prescriptionsDispensed = prescriptionsDispensed; }

    public int getLowStockCount() { return lowStockCount; }
    public void setLowStockCount(int lowStockCount) { this.lowStockCount = lowStockCount; }

    public int getExpiringCount() { return expiringCount; }
    public void setExpiringCount(int expiringCount) { this.expiringCount = expiringCount; }

    public HandoverStatus getStatus() { return status; }
    public void setStatus(HandoverStatus status) { this.status = status; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getAcknowledgedAt() { return acknowledgedAt; }
    public void setAcknowledgedAt(LocalDateTime acknowledgedAt) { this.acknowledgedAt = acknowledgedAt; }

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    public enum HandoverStatus {
        PENDING, ACKNOWLEDGED, ESCALATED
    }
}
